QGS_RASTER_LAYER_GEOMETRY_TYPE = -1
QGS_GROUP_GEOMETRY_TYPE = -2

QGS_POLYGON_GEOMETRY_TYPE = 2
QGS_LINE_GEOMETRY_TYPE = 1
QGS_POINT_GEOMETRY_TYPE = 0


GEOMETRY_TYPES = {
    QGS_POLYGON_GEOMETRY_TYPE: "polygon",
    QGS_LINE_GEOMETRY_TYPE: "line",
    QGS_POINT_GEOMETRY_TYPE: "point",
    QGS_RASTER_LAYER_GEOMETRY_TYPE: "raster",
    QGS_GROUP_GEOMETRY_TYPE: "groups",
}
